config/routes.rb
Rails.application.routes.draw do


  resources :report_comment1s
  resources :report_comment0s
  resources :favor_forums
  resources :favor_reports
  mount Notifications::Engine => "/notifications"
  resources :comment0s
  resources :comment1s

  resources :residence_photos
  resources :identity_photos

  resources :reports

  resources :property_managements
  resources :real_estate_developers

  resources :worktimes do
    member do
      get 'edit_management'
    end
  end

  resources :activities
  resources :penalties
  resources :penalty_types
  resources :forum_complains

  resources :votes, only: [:create]

  resources :forums
  # resources :forums do
  #   member do
  #     put "like" => "forums#upvote"
  #   end
  # end


  resources :residences do
    member do
      get 'show_self'
      get 'edit_self'
    end
  end

  resources :identities do
    member do
      get 'show_self'
      get 'edit_self'
    end
  end

  # resources :communities
  # resources :polls

  #resources :locals
  resources :locals do
    collection do
      get :autocomplete
    end
  end

  resources :districts

  resources :communities do
    member do
      get 'polls', 'forums', 'forum_complains', 'penalties', 'edit_volunteer'
    end
  end

  resources :polls

  # resources :polls do
  #   # end

  resources :users, only: [:index, :show, :edit, :update]

  authenticated :user do
    root to: 'home#index', as: :authenticated_root
  end

  root to: redirect('/u/sign_in')
  devise_for :users, :path => 'u'

  #devise_for :users
  #get 'up' => ''
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/penalty_types_controller.rb
class PenaltyTypesController < ApplicationController
  before_action :set_penalty_type, only: [:show, :edit, :update, :destroy]

  # GET /penalty_types
  # GET /penalty_types.json
  def index
    @penalty_types = PenaltyType.all
  end

  # GET /penalty_types/1
  # GET /penalty_types/1.json
  def show
  end

  # GET /penalty_types/new
  def new
    @penalty_type = PenaltyType.new
  end

  # GET /penalty_types/1/edit
  def edit
  end

  # POST /penalty_types
  # POST /penalty_types.json
  def create
    @penalty_type = PenaltyType.new(penalty_type_params)

    respond_to do |format|
      if @penalty_type.save
        format.html { redirect_to @penalty_type, notice: 'Penalty type was successfully created.' }
        format.json { render :show, status: :created, location: @penalty_type }
      else
        format.html { render :new }
        format.json { render json: @penalty_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /penalty_types/1
  # PATCH/PUT /penalty_types/1.json
  def update
    respond_to do |format|
      if @penalty_type.update(penalty_type_params)
        format.html { redirect_to @penalty_type, notice: 'Penalty type was successfully updated.' }
        format.json { render :show, status: :ok, location: @penalty_type }
      else
        format.html { render :edit }
        format.json { render json: @penalty_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /penalty_types/1
  # DELETE /penalty_types/1.json
  def destroy
    @penalty_type.destroy
    respond_to do |format|
      format.html { redirect_to penalty_types_url, notice: 'Penalty type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_penalty_type
      @penalty_type = PenaltyType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def penalty_type_params
      params.require(:penalty_type).permit(:name, :note)
    end
end

app/helpers/penalty_types_helper.rb
module PenaltyTypesHelper
end

app/views/penalty_types/_form.html.erb
<%= form_for(penalty_type) do |f| %>
  <% if penalty_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(penalty_type.errors.count, "error") %> prohibited this penalty_type from being saved:</h2>

      <ul>
      <% penalty_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :note %>
    <%= f.text_area :note %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/penalty_types/edit.html.erb
<h1>Editing Penalty Type</h1>

<%= render 'form', penalty_type: @penalty_type %>

<%= link_to 'Show', @penalty_type %> |
<%= link_to 'Back', penalty_types_path %>

app/views/penalty_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Penalty Types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Note</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @penalty_types.each do |penalty_type| %>
      <tr>
        <td><%= penalty_type.name %></td>
        <td><%= penalty_type.note %></td>
        <td><%= link_to 'Show', penalty_type %></td>
        <td><%= link_to 'Edit', edit_penalty_type_path(penalty_type) %></td>
        <td><%= link_to 'Destroy', penalty_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Penalty Type', new_penalty_type_path %>

app/views/penalty_types/new.html.erb
<h1>New Penalty Type</h1>

<%= render 'form', penalty_type: @penalty_type %>

<%= link_to 'Back', penalty_types_path %>

app/views/penalty_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @penalty_type.name %>
</p>

<p>
  <strong>Note:</strong>
  <%= @penalty_type.note %>
</p>

<%= link_to 'Edit', edit_penalty_type_path(@penalty_type) %> |
<%= link_to 'Back', penalty_types_path %>