config/routes.rb
Rails.application.routes.draw do


  resources :report_comment1s
  resources :report_comment0s
  resources :favor_forums
  resources :favor_reports
  mount Notifications::Engine => "/notifications"
  resources :comment0s
  resources :comment1s

  resources :residence_photos
  resources :identity_photos

  resources :reports

  resources :property_managements
  resources :real_estate_developers

  resources :worktimes do
    member do
      get 'edit_management'
    end
  end

  resources :activities
  resources :penalties
  resources :penalty_types
  resources :forum_complains

  resources :votes, only: [:create]

  resources :forums
  # resources :forums do
  #   member do
  #     put "like" => "forums#upvote"
  #   end
  # end


  resources :residences do
    member do
      get 'show_self'
      get 'edit_self'
    end
  end

  resources :identities do
    member do
      get 'show_self'
      get 'edit_self'
    end
  end

  # resources :communities
  # resources :polls

  #resources :locals
  resources :locals do
    collection do
      get :autocomplete
    end
  end

  resources :districts

  resources :communities do
    member do
      get 'polls', 'forums', 'forum_complains', 'penalties', 'edit_volunteer'
    end
  end

  resources :polls

  # resources :polls do
  #   # end

  resources :users, only: [:index, :show, :edit, :update]

  authenticated :user do
    root to: 'home#index', as: :authenticated_root
  end

  root to: redirect('/u/sign_in')
  devise_for :users, :path => 'u'

  #devise_for :users
  #get 'up' => ''
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/residence_photo.rb
class ResidencePhoto < ApplicationRecord
  belongs_to :residence

  mount_uploader :photo, ResidencePhotoUploader

  validates :name, presence: true
  validate :photo_size

  default_scope -> { order(created_at: :desc) }

  private

    # Validates the size of an uploaded picture.
    def photo_size
      if photo.size > 1.megabytes
        errors.add(:photo, "照片应该小于 1MB")
      end
    end
    #It does not work on client side...
end

app/controllers/residence_photos_controller.rb
class ResidencePhotosController < ApplicationController
  before_action :set_residence_photo, only: [:show, :edit, :update, :destroy]

  # GET /residence_photos
  # GET /residence_photos.json
  def index
    @residence_photos = ResidencePhoto.all
  end

  # GET /residence_photos/1
  # GET /residence_photos/1.json
  def show
  end

  # GET /residence_photos/new
  def new
    @residence_photo = ResidencePhoto.new
  end

  # GET /residence_photos/1/edit
  def edit
  end

  # POST /residence_photos
  # POST /residence_photos.json
  def create
    @residence_photo = ResidencePhoto.new(residence_photo_params)

    respond_to do |format|
      if @residence_photo.save
        format.html { redirect_to @residence_photo, notice: '照片上传成功！' }
        format.json { render :show, status: :created, location: @residence_photo }
      else
        format.html { render :new }
        format.json { render json: @residence_photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /residence_photos/1
  # PATCH/PUT /residence_photos/1.json
  def update
    respond_to do |format|
      if @residence_photo.update(residence_photo_params)
        format.html { redirect_to @residence_photo, notice: '修改成功！' }
        format.json { render :show, status: :ok, location: @residence_photo }
      else
        format.html { render :edit }
        format.json { render json: @residence_photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /residence_photos/1
  # DELETE /residence_photos/1.json
  def destroy
    @residence_photo.destroy
    respond_to do |format|
      format.html { redirect_to show_self_residence_url(@residence_photo.residence.id), notice: '照片删除成功！' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_residence_photo
      @residence_photo = ResidencePhoto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def residence_photo_params
      params.require(:residence_photo).permit(:residence_id, :name, :photo)
    end
end

app/helpers/residence_photos_helper.rb
module ResidencePhotosHelper
end

app/views/residence_photos/_form.html.erb
<%= simple_form_for(@residence_photo) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :residence %>
    <%= f.input :name %>
    <%= f.input :photo %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/residence_photos/edit.html.erb
<h1>Editing Residence Photo</h1>

<%= render 'form', residence_photo: @residence_photo %>

<%= link_to 'Show', @residence_photo %> |
<%= link_to 'Back', residence_photos_path %>

app/views/residence_photos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Residence Photos</h1>

<table>
  <thead>
    <tr>
      <th>Residence</th>
      <th>Name</th>
      <th>Photo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @residence_photos.each do |residence_photo| %>
      <tr>
        <td><%= residence_photo.residence %></td>
        <td><%= residence_photo.name %></td>
        <td><%= residence_photo.photo %></td>
        <td><%= link_to 'Show', residence_photo %></td>
        <td><%= link_to 'Edit', edit_residence_photo_path(residence_photo) %></td>
        <td><%= link_to 'Destroy', residence_photo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Residence Photo', new_residence_photo_path %>

app/views/residence_photos/new.html.erb
<!-- Modal -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalCenterTitle">常见问题回答</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          <div><!--faq begins-->

            <div class="ask">
              <%= image_tag'icons/ask-red-outline.png', width: '27', height: '27', title: '身份信息', rel: 'tooltip' %> 在上传之前，可以修改照片吗？
            </div>
            <div class="answer">
              <%= image_tag'icons/answer-outline.png', width: '25', height: '25', title: '身份信息', rel: 'tooltip' %> 不可以．最好是用这只手机刚刚拍下的照片．
            </div>

          <p>&nbsp;</p>
              <div class="ask">
                <%= image_tag'icons/ask-red-outline.png', width: '27', height: '27', title: '身份信息', rel: 'tooltip' %> 能够删除刚刚上传的照片吗？
              </div>
              <div class="answer">
                <%= image_tag'icons/answer-outline.png', width: '25', height: '25', title: '身份信息', rel: 'tooltip' %> 在１小时之内可以删除．在申请了验证之后，就不能够删除了．
              </div>

          <p>&nbsp;</p>
              <div class="ask">
                <%= image_tag'icons/ask-red-outline.png', width: '27', height: '27', title: '身份信息', rel: 'tooltip' %> 那些人可以看见咱的个人身份信息和身份证照片？
              </div>
              <div class="answer">
                <%= image_tag'icons/answer-outline.png', width: '25', height: '25', title: '身份信息', rel: 'tooltip' %> １位或者２位＂已经验证＂的，有真实身份的用户，需要看见您的个人身份信息和身份证照片，以验证您的真实身份．普通用户不能够看见您的身份证号码和照片．
              </div>

          <p>&nbsp;</p>
              <div class="ask">
                <%= image_tag'icons/ask-red-outline.png', width: '27', height: '27', title: '身份信息', rel: 'tooltip' %> 在被＂已经验证＂之后，还有哪些人可能看见咱的个人身份信息和身份证照片？
              </div>
              <div class="answer">
                <%= image_tag'icons/answer-outline.png', width: '25', height: '25', title: '身份信息', rel: 'tooltip' %> 在您被＂已经验证＂之后，在特定的情况下，不限于平台管理部，小区物业管理公司代表，小区业主委员会代表，居民委员会代表，当地政府机构，和当地执法机构有可能会查看它们以确定您的真实身份．
              </div>
          <!-- <p>&nbsp;</p>
              <div class="ask">
                <%= image_tag'icons/ask-red-outline.png', width: '27', height: '27', title: '身份信息', rel: 'tooltip' %> 咱能够知道哪些人看过咱的身份证号码和照片？
              </div>
              <div class="answer">
                <%= image_tag'icons/answer-outline.png', width: '25', height: '25', title: '身份信息', rel: 'tooltip' %> 所有对身份证信息的阅读都有记录，您可以知道阅读者的头像和身份．
              </div> -->



          </div><!--faq ends-->
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">关闭</button>
        <!-- <button type="button" class="btn btn-primary">Save changes</button> -->
      </div>
    </div>
  </div>
</div>

<div class="content-box">
  <div>
    <table id="full">
      <tr>
        <td width = "20%">
          <%= link_to image_tag('icons/back-arrow-filled.png', width: '30', height: '30', title: '返回', rel: 'tooltip'), 'javascript:history.back()' %><div id="menu-font">返回上页</div>
        </td>

        <td width = "20%">

        </td>

        <td width = "20">

        </td>

        <td width = "20%"></td>

        <td width = "20%"></td>
      </tr>

    </table>
  </div>

  <div id="page-title">请上传房产证照片</div>

<p>&nbsp;</p>

<div id="index-card">
<%= simple_form_for(@residence_photo) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%#= f.association :identity %>
    <%= f.hidden_field :residence_id, :value => current_user.identity.residence.id %>

    <%= f.input :name, label: '照片名称', collection: [ "房产号页", "名字身份证页", "补充页" ] %>

    <span id="pic">
      <%#= f.input :picture %>
      <%= f.input :photo, label: '上传照片', accept: 'image/jpeg,image/gif,image/png,image/jpg' %>
      <%#= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
      <!-- if accept: 'image/jpeg,image/gif,image/png' is for checking file format on client side, it does not work -->
    </span>
  </div>

  <%= f.button :button do %>
    提交！ <%= image_tag "icons/forward-arrow-filled.png", :size => '25x25', :title => "提交!" %>
  <% end %>
<% end %>
</div>

<p>&nbsp;</p>
<!-- Button trigger modal -->
<button type="button" class="btn btn-link" data-toggle="modal" data-target="#exampleModalCenter">
  <%= image_tag'icons/faq-outline.png', width: '30', height: '30', title: '常见问题', rel: 'tooltip' %> 常见问题回答
</button>

</div>

<script type="text/javascript">
  $('#pic').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 1) {
      alert('Maximum file size is 1MB. Please choose a smaller file.');
    }
  });
</script>

<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>

<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>

app/views/residence_photos/show.html.erb
<div class="content-box">

<div>
  <table id="full">
    <tr>
      <td width = "20%">
        <%= link_to image_tag('icons/back-arrow-filled.png', width: '30', height: '30', title: '返回', rel: 'tooltip'), 'javascript:history.back()' %><div id="menu-font">返回上页</div>
      </td>

      <td width = "20%">

      </td>

      <td width = "20">

      </td>

      <td width = "20%">
        <% if current_user.id == @residence_photo.residence.identity.user.id && Time.zone.now - @residence_photo.created_at < 3600 %>
          <%= link_to image_tag('icons/trash-filled.png', width: '25', height: '25', title: '删除', rel: 'tooltip'), @residence_photo, method: :delete, data: { confirm: '确定删除吗？' } %><div id="menu-font">删除照片</div>
        <% end %>

        <!--1 is one second. 60*60*24 = 86400s/d, thus 3600 is one hour. The user cannot delete it after one hour in production-->
      </td>

      <td width = "20%">
        <%= link_to image_tag('icons/residence-filled.png', width: '30', height: '30', title: '返回', rel: 'tooltip'), :controller => 'residences', :action => 'show_self', :id => @residence_photo.residence.id %><div id="menu-font">居住状况</div>
      </td>
    </tr>

  </table>
</div>

<div id="page-title"><%= @residence_photo.residence.identity.lastname %><%= @residence_photo.residence.identity.firstname %></div>

  <div id="index-card">
    <div id="ago">
      <%= time_ago_in_words(@residence_photo.created_at) %>以前，（１小时之内可以删除）
    </div>
    <p></p>

    <div>
      <%= @residence_photo.name %>
    </div>

    <div>

      <%= image_tag @residence_photo.photo.url, width: '100%', height: '100%' if @residence_photo.photo? %>
    </div>


    <%#= link_to 'Back', identity_photos_path %>
  </div>

</div>

<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>

<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>

<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>

<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>