config/routes.rb
Rails.application.routes.draw do


  resources :report_comment1s
  resources :report_comment0s
  resources :favor_forums
  resources :favor_reports
  mount Notifications::Engine => "/notifications"
  resources :comment0s
  resources :comment1s

  resources :residence_photos
  resources :identity_photos

  resources :reports

  resources :property_managements
  resources :real_estate_developers

  resources :worktimes do
    member do
      get 'edit_management'
    end
  end

  resources :activities
  resources :penalties
  resources :penalty_types
  resources :forum_complains

  resources :votes, only: [:create]

  resources :forums
  # resources :forums do
  #   member do
  #     put "like" => "forums#upvote"
  #   end
  # end


  resources :residences do
    member do
      get 'show_self'
      get 'edit_self'
    end
  end

  resources :identities do
    member do
      get 'show_self'
      get 'edit_self'
    end
  end

  # resources :communities
  # resources :polls

  #resources :locals
  resources :locals do
    collection do
      get :autocomplete
    end
  end

  resources :districts

  resources :communities do
    member do
      get 'polls', 'forums', 'forum_complains', 'penalties', 'edit_volunteer'
    end
  end

  resources :polls

  # resources :polls do
  #   # end

  resources :users, only: [:index, :show, :edit, :update]

  authenticated :user do
    root to: 'home#index', as: :authenticated_root
  end

  root to: redirect('/u/sign_in')
  devise_for :users, :path => 'u'

  #devise_for :users
  #get 'up' => ''
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	#before_filter :authenticate_user!

  def index


    if current_user.identity.nil?
    #1
    else
    #2
      if current_user.identity.status == '已经验证'
      #A
        
        @waitingidentity = Identity.where("status = ? AND ready = ?", '等待验证', true ).size
        @num_identity_read = PublicActivity::Activity.where(owner_id: current_user.id, key: "identity.read").size
        @num_identity_update = PublicActivity::Activity.where(owner_id: current_user.id, key: "identity.update").size

        if current_user.identity.residence.nil?
        #I
          # @waitingidentity = Identity.where("status = ? AND created_at < ?", '等待验证', Time.zone.now - 3600).size
          # @num_identity_read = PublicActivity::Activity.where(owner_id: current_user.id, key: "identity.read").size
          # @num_identity_update = PublicActivity::Activity.where(owner_id: current_user.id, key: "identity.update").size

        elsif current_user.identity.residence.status == '已经验证'
        #II

          @waitingresidence = Residence.where("community_id = ? AND status = ? AND created_at < ? AND role = ?", current_user.identity.residence.community_id, '等待验证', Time.zone.now - 3600, '住家业主').size
          @num_residence_read = PublicActivity::Activity.where(owner_id: current_user.id, key: "residence.read").size
          @num_residence_update = PublicActivity::Activity.where(owner_id: current_user.id, key: "residence.update").size

        end
        #III
      else
      #B

      end
      #D
    end
    #3

  end
end
# order is very important.

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<!-- Modal -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalCenterTitle">常见问题回答</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          <div><!--faq begins-->

            <div class="ask">
              <%= image_tag'icons/ask-red-outline.png', width: '27', height: '27', title: '身份信息', rel: 'tooltip' %> 为啥需要咱填写真实的个人身份信息？
            </div>
            <div class="answer">
              <%= image_tag'icons/answer-outline.png', width: '25', height: '25', title: '身份信息', rel: 'tooltip' %> “小区记忆”内的业主和居民们只愿意与有真实身份的其他小区业主和居民讨论小区事务．更重要的是要保障小区重大议题投票的权威性．
            </div>

          <p>&nbsp;</p>
              <div class="ask">
                <%= image_tag'icons/ask-red-outline.png', width: '27', height: '27', title: '身份信息', rel: 'tooltip' %> 如果咱的个人身份信息得到了“已经验证”，有些什么权限？
              </div>
              <div class="answer">
                <%= image_tag'icons/answer-outline.png', width: '25', height: '25', title: '身份信息', rel: 'tooltip' %> 可以验证她他人身份信息的真实性，可以阅读更多版块的信息．
              </div>

          <p>&nbsp;</p>
              <div class="ask">
                <%= image_tag'icons/ask-red-outline.png', width: '27', height: '27', title: '身份信息', rel: 'tooltip' %> 如果咱的居住状况得到了“已经验证”，有些什么权限？
              </div>
              <div class="answer">
                <%= image_tag'icons/answer-outline.png', width: '25', height: '25', title: '身份信息', rel: 'tooltip' %> 可以验证其他同一小区的业主邻居用户，可以进入自己的小区阅读，讨论，和投票．
              </div>

          <p>&nbsp;</p>
              <div class="ask">
                <%= image_tag'icons/ask-red-outline.png', width: '27', height: '27', title: '身份信息', rel: 'tooltip' %> 为啥需要咱来验证其他邻居业主的真实身份信息？
              </div>
              <div class="answer">
                <%= image_tag'icons/answer-outline.png', width: '25', height: '25', title: '身份信息', rel: 'tooltip' %> “小区记忆”是由小区业主居民们来自我管理的，就像小区家园应该由小区业主居民们来自我管理一样．
              </div>

          <p>&nbsp;</p>
              <div class="ask">
                <%= image_tag'icons/ask-red-outline.png', width: '27', height: '27', title: '身份信息', rel: 'tooltip' %> 咱的头像是怎么回事？
              </div>
              <div class="answer">
                <%= image_tag'icons/answer-outline.png', width: '25', height: '25', title: '身份信息', rel: 'tooltip' %> 您的头像叫“万花筒”。它是根据您自己本身独特的信息，电脑系统自动生成的。您的头像是永久存在的，而且独一无二的．
              </div>

          <p>&nbsp;</p>
              <div class="ask">
                <%= image_tag'icons/ask-red-outline.png', width: '27', height: '27', title: '身份信息', rel: 'tooltip' %> 咱的头像可以自己更改吗？
              </div>
              <div class="answer">
                <%= image_tag'icons/answer-outline.png', width: '25', height: '25', title: '身份信息', rel: 'tooltip' %> 不能．如果您的头像被任意地更改，同一小区里的业主居民用户就很难认识您，记住您了．为了保护您的隐私，小区外的用户只可见您的头像，不可见您的姓名．
              </div>

          </div><!--faq ends-->
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">关闭</button>
        <!-- <button type="button" class="btn btn-primary">Save changes</button> -->
      </div>
    </div>
  </div>
</div>
<div class="content-box">

  <% if current_user.identity.nil? %>
    <div>
      <%= link_to image_tag('icons/800.jpg', width: '100%', height: '100%', title: '用户服务', rel: 'tooltip'), root_path %>
    </div>
  <% elsif current_user.identity.residence.nil? %>
    <div>
      <%= link_to image_tag('icons/800.jpg', width: '100%', height: '100%', title: '用户服务', rel: 'tooltip'), root_path %>
    </div>
  <% else %>
    <div>
      <%= link_to image_tag('icons/800.jpg', width: '100%', height: '100%', title: '用户服务', rel: 'tooltip'), root_path %>
    </div>
  <% end %>
<p></p>

  <% if current_user.identity.nil? %>
  <!--1-->
    <div id="index-card" class="bold">
      <div>尊敬的无名侠：欢迎您来到“小区微博”！</div>
      <p></p>
      <div>家园小区是咱们业主自己的小区，自己的家园，自己的财产，由咱们自己作主！</div>
    </div>

    <p>&nbsp;</p>

    <div id="section-title">身份状况</div>

    <div id="index-card">
      请填写您真实的个人身份信息 <%= link_to image_tag('icons/forward-arrow-filled.png', width: '25', height: '25', title: '身份信息', rel: 'tooltip'), :controller => 'identities', :action => 'new', :id => current_user.id %>
    </div>

  <% elsif current_user.identity.ready != true %>
    <div id="index-card" class="bold">
      <div><%= current_user.identity.lastname %><%= current_user.identity.firstname %><% if current_user.identity.sex == '男'%>先生<% else %>女士<% end %>：欢迎您来到“小区微博”！</div>
      <p></p>
      <div>家园小区是咱们业主自己的小区，自己的家园，自己的财产，由咱们自己作主！</div>
    </div>
    <p>&nbsp;</p>

    <div id="section-title">身份状况</div>
    <div id="index-card" class="bold">
      <div id="ago">
        <%= time_ago_in_words(current_user.identity.updated_at) %>以前，
      </div>
  <p></p>

      <div>请完善个人身份信息 <%= link_to image_tag('icons/forward-arrow-filled.png', width: '25', height: '25', title: '身份信息', rel: 'tooltip'), :controller => 'identities', :action => 'show_self', :id => current_user.identity.id %></br>

      </div>
    </div>

  <% else %>
  <!--2-->
    <div id="index-card" class="bold">
      <div><%= current_user.identity.lastname %><%= current_user.identity.firstname %><% if current_user.identity.sex == '男'%>先生<% else %>女士<% end %>：欢迎您来到“小区微博”！</div>
      <p></p>
      <div>家园小区是咱们业主自己的小区，自己的家园，自己的财产，由咱们自己作主！</div>
    </div>
    <p>&nbsp;</p>

    <div id="section-title">身份状况</div>
    <div id="index-card" class="bold">
      <div id="ago">
        <%= time_ago_in_words(current_user.identity.updated_at) %>以前，
      </div>
<p></p>

      <div>您的身份是"<%= current_user.identity.status %>"，请查看 <%= link_to image_tag('icons/id-card-filled.png', width: '25', height: '25', title: '身份信息', rel: 'tooltip'), :controller => 'identities', :action => 'show_self', :id => current_user.identity.id %></br>

      </div>
    </div>
<%#= @waitingidentity %>
    <% if current_user.identity.status == '已经验证' && @waitingidentity == 0 %>
      <!--nothingness-->
    <% elsif current_user.identity.status == '已经验证' && @num_identity_read < 10 && @num_identity_update < 20 && @waitingidentity != 0 %>

        <div>
          有一位“等待验证”的新用户，请帮忙验证她他的真实身份 <%= link_to image_tag('icons/forward-arrow-filled.png', width: '25', height: '25', title: '身份信息', rel: 'tooltip'), :controller => 'identities', :action => 'index', :id => current_user.identity.id %>
        </div>
      </div>

    <% else %>
    <!--B -->
    <% end %>
    <!--C-->
    <p>&nbsp;</p>


    <% if current_user.identity.status == '已经验证' && current_user.residence.nil? %>
      <div id="section-title">居住状况</div>

      <div id="index-card" class="bold">
        <div>

          请填写您的居住状况 <%= link_to image_tag('icons/forward-arrow-filled.png', width: '25', height: '25', title: '居住状况', rel: 'tooltip'), :controller => 'residences', :action => 'new', :id => current_user.id %>
        </div>
      </div>
    <% elsif current_user.identity.status != '已经验证' && current_user.residence.nil? %>
    <!--nothingness -->
    <% else %>
        <div id="section-title">居住状况</div>

          <div id="index-card" class="bold">
            <div id="ago"><%= time_ago_in_words(current_user.residence.updated_at) %>以前，</div>
<p></p>
            <div>
              您的是"<%= current_user.residence.status %>"，请查看 <%= link_to image_tag('icons/residence-filled.png', width: '25', height: '25', title: '居住状况', rel: 'tooltip'), :controller => 'residences', :action => 'show_self', :id => current_user.identity.residence.id %>
            </div>
          </div>

          <% if current_user.identity.residence.status == '已经验证' %>
            <%#= @waitingidentity %><%#= @waitingresidence %><%#= @num_residence_read %><%#= @num_residence_update %>
            <% if @num_residence_read < 1 && @num_residence_update < 2 && @waitingresidence != 0 %>
              <div id="index-card">
                请帮忙验证一位在您小区居住的，正在“等待认证”的邻居 <%= link_to image_tag('icons/forward-arrow-filled.png', width: '25', height: '25', title: '验证居住状况', rel: 'tooltip'), :controller => 'residences', :action => 'index', :id => current_user.residence.id %>
              </div>
            <% else %>
            <!--nothingness-->
            <% end %>

          <% else %>
            <!--nothingness -->
          <% end %>

    <% end %>

  <% end %>
  <!--3-->

  <p>&nbsp;</p>
  <!-- Button trigger modal -->
  <button type="button" class="btn btn-link" data-toggle="modal" data-target="#exampleModalCenter">
    <%= image_tag'icons/faq-outline.png', width: '30', height: '30', title: '记录投诉', rel: 'tooltip' %> 常见问题回答
  </button>

  <div class="bottom-menu">
    <table id="full">
      <tr>
        <td width = "20%">
        </td>

        <td width = "20%">
        </td>

        <td width = "20">

            <% if current_user.identity.nil? or current_user.identity.status != '已经验证' or current_user.identity.residence.nil? or current_user.identity.residence.status != '已经验证' %>

            <% else %>
              <div class="btn-group dropup">
                <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <div><%= image_tag('icons/logo.png', width: '35', height: '35', title: '更多菜单', rel: 'tooltip') %></div>

                </button>

                <div class="dropdown-menu">
                  <div>
                    <%= link_to image_tag('icons/xiaoqu-red-heart-filled.png', width: '30', height: '30', title: '返回', rel: 'tooltip'), :controller => 'communities', :action => 'show', :id => current_user.identity.residence.community_id %> <%= link_to "咱的小区", :controller => 'communities', :action => 'show', :id => current_user.identity.residence.community_id %>
                  </div>
                  <div>
                    <%= link_to image_tag('icons/forum-filled.png', width: '30', height: '30', title: '小区论坛', rel: 'tooltip'), forums_path %> <%= link_to "小区论坛", forums_path %>
                  </div>
                  <div>
                    <%#= link_to image_tag('icons/pinwheel-filled.png', width: '30', height: '30', title: '意见调查', rel: 'tooltip'), polls_path %> <%#= link_to "意见调查", polls_path %>
                  </div>
                  <div>
                    <%= link_to image_tag('icons/roadsign-filled.png', width: '30', height: '30', title: '意见调查', rel: 'tooltip'), polls_path %> <%= link_to "意见调查", polls_path %>
                  </div>


                  <div>
                    <%= link_to image_tag('icons/atwork-filled.png', width: '30', height: '30', title: '记录投诉', rel: 'tooltip'), reports_path %> <%= link_to "记录投诉", reports_path %>
                  </div>


                </div>
              </div>

          <% end %>
        </td>

        <td width = "20%"></td>

        <td width = "20%" id="image-holder"></td>
      </tr>

    </table>
  </div>
</div> <!--content-box end-->

<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>


<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>