config/routes.rb
Rails.application.routes.draw do


  resources :report_comment1s
  resources :report_comment0s
  resources :favor_forums
  resources :favor_reports
  mount Notifications::Engine => "/notifications"
  resources :comment0s
  resources :comment1s

  resources :residence_photos
  resources :identity_photos

  resources :reports

  resources :property_managements
  resources :real_estate_developers

  resources :worktimes do
    member do
      get 'edit_management'
    end
  end

  resources :activities
  resources :penalties
  resources :penalty_types
  resources :forum_complains

  resources :votes, only: [:create]

  resources :forums
  # resources :forums do
  #   member do
  #     put "like" => "forums#upvote"
  #   end
  # end


  resources :residences do
    member do
      get 'show_self'
      get 'edit_self'
    end
  end

  resources :identities do
    member do
      get 'show_self'
      get 'edit_self'
    end
  end

  # resources :communities
  # resources :polls

  #resources :locals
  resources :locals do
    collection do
      get :autocomplete
    end
  end

  resources :districts

  resources :communities do
    member do
      get 'polls', 'forums', 'forum_complains', 'penalties', 'edit_volunteer'
    end
  end

  resources :polls

  # resources :polls do
  #   # end

  resources :users, only: [:index, :show, :edit, :update]

  authenticated :user do
    root to: 'home#index', as: :authenticated_root
  end

  root to: redirect('/u/sign_in')
  devise_for :users, :path => 'u'

  #devise_for :users
  #get 'up' => ''
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :user
  belongs_to :identity

  belongs_to :province
  belongs_to :city
  belongs_to :district
  belongs_to :local
  belongs_to :community

  has_many :favor_reports, dependent: :destroy

  has_many :report_comment0s, dependent: :destroy

  validates :building,  presence: true, length: { maximum: 6 }
  validates :floor,  presence: true, length: { maximum: 6 }
  validates :surround,  presence: true
  validates :unit, length: { maximum: 6 }
  validates :facility_type, length: { maximum: 6 }

  validates :entity,  presence: true
  validates :representative,  presence: true, length: { maximum: 6 }
  validates :sex,  presence: true
  validates :contact_type,  presence: true

  validates :attitude,  presence: true
  validates :fix_time,  presence: true

  validates :note1, presence: true, length: { minimum: 6, maximum: 140 }

  validates :note2, length: { maximum: 140 }

  default_scope -> { order(closed: :asc, created_at: :desc) }

  before_validation do
    self.average = ((attitude.to_i + fix_time.to_i + fix_result.to_i)/3.0).round(2)
  end

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: [:show, :edit, :update, :destroy]

  # GET /reports
  # GET /reports.json
  def index

    @reports = Report.where("community_id = ?", current_user.identity.residence.community_id).paginate(:page => params[:page], :per_page => 10)

    # if @reports = Report.where("community_id = ? AND closed = ? AND entity = ?", current_user.identity.residence.community_id, true, "物业管理公司").first
    #
    #   @closed_average1 = Report.where("community_id = ? AND closed = ? AND entity = ?", current_user.identity.residence.community_id, true, "物业管理公司").average("average").round(2)
    #
    #   @reports = Report.where("community_id = ?", current_user.identity.residence.community_id)
    #
    # else
    #   @closed_average1 = 0
    #
    #   @reports = Report.where("community_id = ?", current_user.identity.residence.community_id)
    #
    # end

    #@closed_average2 = Report.where("community_id = ? AND closed = ? AND entity = ?", current_user.identity.residence.community_id, true, "房地产开发商").average("average").round(2)
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
  end

  # GET /reports/new
  def new
    @report = Report.new
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(report_params)

    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, notice: '成功创建新汇报！' }
        format.json { render :show, status: :created, location: @report }
      else
        format.html { render :new }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to @report, notice: '成功鉴定最终结果！' }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html { render :edit }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url, notice: '成功删除一个汇报！' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params.require(:report).permit(:user_id, :building, :surround, :floor, :facility_type, :unit, :entity, :representative, :sex, :contact_type, :fix_date, :attitude, :fix_time, :fix_result, :average, :note1, :identity_id, :closed, :note2, :province_id, :city_id, :district_id, :local_id, :community_id)
    end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_form.html.erb
<%= simple_form_for(@report) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :user %>
    <%= f.input :building %>
    <%= f.input :surround %>
    <%= f.input :floor %>
    <%= f.input :facility_type %>
    <%= f.input :unit %>
    <%= f.input :entity %>
    <%= f.input :representative %>
    <%= f.association :sex %>
    <%= f.input :contact_type %>
    <%= f.input :fix_date %>
    <%= f.input :attitude %>
    <%= f.input :fix_time %>
    <%= f.input :fix_result %>
    <%= f.input :average %>
    <%= f.input :note1 %>
    <%= f.association :identity %>
    <%= f.input :closed %>
    <%= f.input :note2 %>
    <%= f.association :province %>
    <%= f.association :city %>
    <%= f.association :district %>
    <%= f.association :local %>
    <%= f.association :community %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/reports/_report.html.erb
<div><!--big if begins -->
  <% if @reports.nil? %>
<!-- why not .nil? probably because @reports have other records in a different community. And .empty? means @reports do not have anything matching this community-->
    您的小区还没有任何汇报。您来做第一人吧！

  <% else %>

        <%# @reports.each do |report| %>
        <p></p>

          <div id="index-card">
            <table width="100%">
              <tr>
                <td width="80%">
                  <div id="emphasized-date">
                    <%= (report.created_at).strftime("%Y年%m月%d日 %H:%M") %>
                  </div>
                </td>

                <td width="20%">
                  <% if report.closed == true %>
                  <%= image_tag('icons/star-red-outline.png', width: '25', height: '25', title: '工作中...', rel: 'tooltip') %>
                  <% else %>
                  <%= image_tag('icons/atwork-red-outline.png', width: '25', height: '25', title: '工作中...', rel: 'tooltip') %>
                  <% end %>
                </td>
              </tr>
            </table>

            <table>
              <tr>
                <td width="20%">
                  <% if report.user.identity.sex == "女" %>
                    <%= gravatar_female report.user %>
                  <% elsif report.user.identity.sex == "男" %>
                    <%= gravatar_male report.user %>
                  <% end %>
                </td>
                <td width="20%">
                  <span id="name"><%= link_to report.user.identity.lastname + report.user.identity.firstname, :controller => 'users', :action => 'show', :id => report.user_id %></span>
                </td>

                <td width="20%"><span id="bold"><%= report.user.identity.residence.role %></span></td>
                <td width="20%"><%= report.user.identity.age_group %>0后</td>
                <td width="20%">1234<%#= poll.user.identity.residence.community.local.district.city.name %></td>

              </tr>
            </table>
            <p></p>
            <div>
              汇报了在第<span id="data-entry"><%= report.building %></span>栋建筑的<% if report.floor? %><span id="data-entry">第<%= report.floor %></span>层楼<% end %>，<span id="data-entry"><%= report.surround %></span><% if report.unit? %>邻居单元号，<span id="data-entry"><%= report.unit %></span><% else %><span id="data-entry"><%= report.facility_type %></span>:<% end %></br>
            </div>

            <!-- <div id="note">“<%#= report.note1 %>”</div> -->


            <hr width="90%"></hr>

            <% if report.closed == true %>
            <!-- <table>
              <tr>
                <td width="20%">
                  <% if report.identity.sex == "女" %>
                    <%= gravatar_female report.identity.user %>
                  <% elsif report.identity.sex == "男" %>
                    <%= gravatar_male report.identity.user %>
                  <% end %>


                </td>
                <td width="20%"><span id="name"><%= link_to report.identity.lastname + report.identity.firstname, :controller => 'users', :action => 'show', :id => report.user_id %></span></td>

                <td width="20%"><span id="bold"><%= report.identity.residence.role %></span></td>
                <td width="20%"><%= report.identity.age_group %>0后</td>
                <td width="20%"></td>
              </tr>
            </table>

            <p></p>
              <div>鉴定了最后的结果，</div>

              <p></p>
              <div id="note">“<%= report.note2 %>”</div>

                <hr width="90%"></hr> -->

              <div>
                <%= image_tag "icons/abacus-red-outline.png", :size => '20x20', :title => "计算" %> <span id="section-title"><%= report.entity %>本次平均得分:</span><%= report.average %> <%= image_tag('icons/star-red-outline.png', width: '20', height: '20', title: '星', rel: 'tooltip') %>
              </div>

            <% else %>

            <% end %><!--if report.closed ends-->

            <table width="100%">
              <tr>
                <td width="20%"><%= image_tag('icons/comment0-plus-filled.png', width: '30', height: '30', title: '详情', rel: 'tooltip') %><div id="menu-font"><%= report.report_comment0s.size %>评论</div>

                </td>

                <td width="20%" id="image-holder">
                  <%#= image_tag('icons/like-plus-filled.png', width: '25', height: '25', title: '工作中...', rel: 'tooltip') %>
                </td>

                <td width="20%" id="image-holder">

                </td>

                <td width="20%" id="image-holder">

                </td>
                <td width="20%">
                    <%#= link_to '详情', report %> <%= link_to image_tag('icons/forward-arrow-filled.png', width: '30', height: '30', title: '详情', rel: 'tooltip'), report %><div id="menu-font">此贴详情</div>
                </td>
              </tr>
            </table>
          </div><!--index-card ends-->
        <%# end %><!--@reports.each do |report| ends-->
    </div><!--report div ends-->

    <p>&nbsp;</p>
  <% end %> <!-- report empty ends-->
</div><!--big if ends -->

app/views/reports/edit.html.erb
<!-- Modal -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalCenterTitle">常见问题回答</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          <div><!--faq begins-->

            <div class="ask">
              <%= image_tag'icons/ask-red-outline.png', width: '27', height: '27', title: '身份信息', rel: 'tooltip' %> 如果一个汇报迟迟没有得到解决，作为"结果鉴定者"，咱能结束这个汇报，并且给它打０分吗？
            </div>
            <div class="answer">
              <%= image_tag'icons/answer-outline.png', width: '25', height: '25', title: '身份信息', rel: 'tooltip' %> 如果这个汇报没有得到解决，就不要给它最后打分来结束这个汇报，直到这个汇报得到解决为止，无论多久．这样，咱们的数据库就会得到一个＂汇报解决比＂．举例来讲，如果在一年中，总共有1000个汇报，而相关机构或者个人仅仅解决了600个，那这一年来的＂汇报解决比＂就是60%，这也是不及格的．
            </div>

          <p>&nbsp;</p>
              <div class="ask">
                <%= image_tag'icons/ask-red-outline.png', width: '27', height: '27', title: '身份信息', rel: 'tooltip' %> 某个汇报已经得到解决，在给它最后打分之前，作为"结果鉴定者"还应该注意什么吗？
              </div>
              <div class="answer">
                <%= image_tag'icons/answer-outline.png', width: '25', height: '25', title: '身份信息', rel: 'tooltip' %> 请仔细检查此汇报是否真的得到了解决？如果不满意，是否可以让相关机构或者个人重新解决？如果相关机构或者个人坚持认为已经解决，请多多参考“汇报发起人”和“汇报追踪者”们对此相关机构或者个人的意见．
              </div>

          <p>&nbsp;</p>
              <div class="ask">
                <%= image_tag'icons/ask-red-outline.png', width: '27', height: '27', title: '身份信息', rel: 'tooltip' %> 选“是”以后，已经提交咱的打分，还能反悔吗？
              </div>
              <div class="answer">
                <%= image_tag'icons/answer-outline.png', width: '25', height: '25', title: '身份信息', rel: 'tooltip' %> 这就是此汇报的最终结果，无法反悔．所以请慎重打分．
              </div>

          <p>&nbsp;</p>
              <div class="ask">
                <%= image_tag'icons/ask-red-outline.png', width: '27', height: '27', title: '身份信息', rel: 'tooltip' %> “汇报发起人”与"结果鉴定者"可以是同一位业主吗？
              </div>
              <div class="answer">
                <%= image_tag'icons/answer-outline.png', width: '25', height: '25', title: '身份信息', rel: 'tooltip' %> 可以，但也可以是不同的业主．
              </div>

              <!-- <p>&nbsp;</p>
                  <div class="ask">
                    <%= image_tag'icons/ask-red-outline.png', width: '27', height: '27', title: '身份信息', rel: 'tooltip' %> 咱愿意当小区义工管理员，如何申请？
                  </div>
                  <div class="answer">
                    <%= image_tag'icons/answer-outline.png', width: '25', height: '25', title: '身份信息', rel: 'tooltip' %> 首先，您必须是小区＂业主＂的身份才能申请。咱们正在整理出详细的申请办法，谢谢耐心等待！
                  </div> -->

          </div><!--faq ends-->
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">关闭</button>
        <!-- <button type="button" class="btn btn-primary">Save changes</button> -->
      </div>
    </div>
  </div>
</div>

<div class="content-box">

  <div>
    <table id="full">
      <tr>
        <td width = "20%">
          <%= link_to image_tag('icons/back-arrow-filled.png', width: '30', height: '30', title: '返回', rel: 'tooltip'), 'javascript:history.back()' %><div id="menu-font">返回上页</div>
        </td>

        <td width = "20%">

        </td>

        <td width = "20">

        </td>

        <td width = "20%"></td>

        <td width = "20%"><%= link_to image_tag('icons/atwork-filled.png', width: '25', height: '25', title: '返回', rel: 'tooltip'), reports_path %><div id="menu-font">全部投诉</div></td>
      </tr>

    </table>
  </div>

  <div id="page-title">服务已经完成？请您鉴定结果</div>

  <p></p>

  <div id="index-card">
    <table width="100%">
      <tr>
        <td width="80%">
          <div id="emphasized-date">
            <%= (@report.created_at).strftime("%Y年%m月%d日 %H:%M") %>
          </div>
        </td>

        <td width="20%">
          <% if @report.closed == true %>
          <%= image_tag('icons/star-red-outline.png', width: '25', height: '25', title: '工作中...', rel: 'tooltip') %>
          <% else %>
          <%= image_tag('icons/atwork-red-outline.png', width: '25', height: '25', title: '工作中...', rel: 'tooltip') %>
          <% end %>
        </td>
      </tr>
    </table>

<p></p>
    <div>
        <span id="data-entry"><%= @report.user.identity.lastname %><%= @report.user.identity.firstname %></span>业主，＂汇报者＂通过<span id="data-entry"><%= @report.contact_type %></span>的方式，向<span id="data-entry"><%= @report.entity %></span>的<span id="data-entry"><%= @report.representative %></span><% if @report.sex == '男' %>先生<% else %>女士<% end %>汇报了在第<span id="data-entry"><%= @report.building %></span>栋建筑的<% if @report.floor? %><span id="data-entry"><%= @report.floor %></span>层楼<% end %>，<span id="data-entry"><%= @report.surround %></span>的<% if @report.unit? %>邻居单元号，<span id="data-entry"><%= @report.unit %></span><% else %><span id="data-entry"><%= @report.facility_type %></span>: <% end %>
    </div>
<p></p>
    <div id="note">
      “<%= @report.note1 %>”
    </div>
<p></p>
    <div>

      <span id="data-entry"><%= @report.representative %></span><% if @report.sex == '男' %>先生<% else %>女士<% end %>承诺在<span id="emphasized-date"><%= (@report.fix_date).strftime("%Y年%m月%d日") %></span>以前，完全解决此事。

    </div>
<p></p>
    <div>
      <span id="data-entry"><%= @report.user.identity.lastname %><%= @report.user.identity.firstname %></span>，对<span id="data-entry"><%= @report.entity %></span>打分如下：
      </p>

    </div>

    <div id="score">
      1/3，意愿和态度:

      <%= @report.attitude %>分 <%= image_tag('icons/star-red-outline.png', width: '20', height: '20', title: '时光飞驰中', rel: 'tooltip') %></br>

      2/3，承诺解决日期:
      <%= @report.fix_time %>分 <%= image_tag('icons/star-red-outline.png', width: '20', height: '20', title: '时光飞驰中', rel: 'tooltip') %>

    </div>
</div>
<%= image_tag('icons/clock-red-outline.png', width: '25', height: '25', title: '时光飞驰中', rel: 'tooltip') %>
  <div id="index-card">

    <div>
      服务已经完成？请您作为＂鉴定者＂，打出最后一项评分：
    </div>
    <p></p>

    <%= simple_form_for(@report) do |f| %>
      <%#= render 'shared/errors', object: f.object %>
      <%= f.error_notification %>

      <div class="form-inputs">
        <%= f.hidden_field :identity_id, :value => current_user.identity.id %>
        <!--user_id to create, and identity_id to update -->
        <div id="score">
          3/3，最终解决结果</br>
          <%= f.collection_radio_buttons :fix_result, [[0.0, '打赏０分，什么都没做！'], [1.0, '打赏１分，非常不满意。'], [2.0, '打赏２分，不太满意。'], [3.0, '打赏３分，基本满意吧。'], [4.0, '打赏４分，非常满意。'], [5.0, '打赏５分，几乎完美！']], :first, :last %></br>
        </div>
        <%#= f.text_area :note2, class: "form-control", placeholder: "描述详细情况。最少5个字，最多280个字。必填！", rows: 3 %>
        <%= f.input :note2, label: false, as: :text, placeholder: '描述详细情况。最少6个字，最多140个字。' %>
        <%= f.hidden_field :closed, :value => true %>

        <p>&nbsp;</p>
        <%= f.button :button do %>
          提交！ <%= image_tag "icons/forward-arrow-filled.png", :size => '25x25', :title => "提交" %>
        <% end %>
      </div>
    <% end %>
  </div>

  <p>&nbsp;</p>
  <!-- Button trigger modal -->
  <button type="button" class="btn btn-link" data-toggle="modal" data-target="#exampleModalCenter">
    <%= image_tag'icons/faq-outline.png', width: '30', height: '30', title: '记录投诉', rel: 'tooltip' %> 常见问题回答
  </button>

</div>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>

<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>

<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>

<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>

app/views/reports/index.html.erb
<div class="content-box">

  <div>
    <table id="full">
      <tr>
        <td width = "20%">
          <%= link_to image_tag('icons/back-arrow-filled.png', width: '30', height: '30', title: '返回', rel: 'tooltip'), 'javascript:history.back()' %><div id="menu-font">返回上页</div>
        </td>

        <td width = "20%">

        </td>

        <td width = "20">

        </td>

        <td width = "20%"></td>

        <td width = "20%"><%= link_to image_tag('icons/xiaoqu-red-heart-filled.png', width: '30', height: '30', title: '返回', rel: 'tooltip'), :controller => 'communities', :action => 'show', :id => current_user.identity.residence.community_id %><div id="menu-font">咱的小区</div></td>
      </tr>

    </table>
  </div>

<div id="page-title">汇报记录</div>

  <%= will_paginate @reports %>
  <div id="reports">

      <%= render @reports %>

  </div>

  <%= will_paginate @reports, class: "pagination pagination-lg" %>

  <div class="bottom-menu">
    <table id="full">
      <tr>
        <td width = "20%">

        </td>

        <td width = "20%">

        </td>

        <td width = "20">

            <%= link_to image_tag('icons/atwork-plus-filled.png', width: '35', height: '35', title: '请添加新汇报', rel: 'tooltip'), new_report_path %><div id="menu-font">添新汇报</div>

        </td>

        <td width = "20%">

        </td>

        <td width = "20%">

        </td>
      </tr>

    </table>
  </div>

</div><!-- content-box ends -->
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>

<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>

<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>

<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>